import { IBasicTableDemoColumn } from "../type";

const useTableData = () => {
  const tableData: IBasicTableDemoColumn[] = [
    {
      id: 1,
      name: "张一",
      money: 123,
      address: "广东省东莞市长安镇",
      state: "成功",
      date: "2019-11-1",
      thumb: "https://lin-xin.gitee.io/images/post/wms.png",
    },
    {
      id: 2,
      name: "李二",
      money: 456,
      address: "广东省广州市白云区",
      state: "成功",
      date: "2019-10-11",
      thumb: "https://lin-xin.gitee.io/images/post/node3.png",
    },
    {
      id: 3,
      name: "张三",
      money: 123,
      address: "广东省东莞市长安镇",
      state: "成功",
      date: "2019-11-1",
      thumb: "https://lin-xin.gitee.io/images/post/wms.png",
    },
    {
      id: 4,
      name: "李四",
      money: 456,
      address: "广东省广州市白云区",
      state: "成功",
      date: "2019-10-11",
      thumb: "https://lin-xin.gitee.io/images/post/node3.png",
    },
    {
      id: 5,
      name: "张三",
      money: 123,
      address: "广东省东莞市长安镇",
      state: "成功",
      date: "2019-11-1",
      thumb: "https://lin-xin.gitee.io/images/post/wms.png",
    },
    {
      id: 6,
      name: "李四",
      money: 456,
      address: "广东省广州市白云区",
      state: "失败",
      date: "2019-10-11",
      thumb: "https://lin-xin.gitee.io/images/post/node3.png",
    },
    {
      id: 7,
      name: "张三",
      money: 123,
      address: "广东省东莞市长安镇",
      state: "成功",
      date: "2019-11-1",
      thumb: "https://lin-xin.gitee.io/images/post/wms.png",
    },
    {
      id: 8,
      name: "李四",
      money: 456,
      address: "广东省广州市白云区",
      state: "成功",
      date: "2019-10-11",
      thumb: "https://lin-xin.gitee.io/images/post/node3.png",
    },
    {
      id: 9,
      name: "张三",
      money: 123,
      address: "广东省东莞市长安镇",
      state: "成功",
      date: "2019-11-1",
      thumb: "https://lin-xin.gitee.io/images/post/wms.png",
    },
    {
      id: 10,
      name: "李四",
      money: 456,
      address: "广东省广州市白云区",
      state: "成功",
      date: "2019-10-11",
      thumb: "https://lin-xin.gitee.io/images/post/node3.png",
    },
    {
      id: 11,
      name: "张三",
      money: 123,
      address: "广东省东莞市长安镇",
      state: "成功",
      date: "2019-11-1",
      thumb: "https://lin-xin.gitee.io/images/post/wms.png",
    },
    {
      id: 12,
      name: "李四",
      money: 456,
      address: "广东省广州市白云区",
      state: "成功",
      date: "2019-10-11",
      thumb: "https://lin-xin.gitee.io/images/post/node3.png",
    },
  ];
  return {
    tableData,
  };
};

export default useTableData;
